## Numpy Quiz1

Q1. arange(), reshape() 이용 1차원 2차원 3차원 배열 생성

In [ ]:
import numpy as np

arr_1d = np.arange(10)
print(arr_1d)
arr_2d = np.arange(12).reshape(3, 4)
print(arr_2d)
arr_3d = np.arange(24).reshape(2, 3, 4)
print(arr_3d)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


Q2. reshape(-1,-1)을 이용 1차원을 2차원, 3차원으로 2차원을 1차원 3차원으로 3차원을 1차원 2차원으로 변환

In [ ]:
import numpy as np

# 1차원 배열 생성
array1d = np.array([1, 2, 3, 4, 5, 6])
# 2차원 배열 생성
array2d = np.array([[1, 2], [3, 4], [5, 6]])
# 3차원 배열 생성
array3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# 1차원을  2차원 배열로 변환
array2d = array1d.reshape(-1, 2)
print(array2d)

# 2차원을 1차원 배열로 변환
array1d = array2d.reshape(-1)
print(array1d)

# 3차원을 1차원 배열로 변환
array1d = array3d.reshape(-1)
print(array1d)

# 3차원을 2차원 배열로 변환
array2d = array3d.reshape(-1, 4)
print(array2d)

# 2차원 3차원 배열로 변환
array3d = array2d.reshape(-1, 2, 2)
print(array3d)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Q3. Q1 1차원 배열을 실수형으로 변환

In [ ]:
arr_1d = arr_1d.astype('float')

Q4. Q1 1차원 배열의 dtype을 확인

In [ ]:
print(arr_1d, arr_1d.dtype)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] float64


Q5. 주어진 배열에서 음수 값을 모두 0으로 변경하세요.

arr = np.array([-5, -3, -1, 0, 1, 3, 5])

In [ ]:
arr = np.array([-5, -3, -1, 0, 1, 3, 5])
arr[arr < 0] = 0
print(arr)

[0 0 0 0 1 3 5]


Q6. 1 ~ 100 까지 배열에서 3의 배수인 것만을 출력

In [ ]:
arr = np.arange(1, 101)
a = arr[arr % 3 == 0]
print(a)

[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]


Q7. 1 ~ 100 까지 배열에서 5의 배수이면서 2의 배수인 것만을 출력

In [ ]:
arr = np.arange(1, 101)
a = arr[(arr % 5 == 0) & (arr % 2 == 0)]
print(a)

[ 10  20  30  40  50  60  70  80  90 100]


Q8. 1 ~ 100 까지 배열에서 3의 배수이거나 5의 배수인 것만을 출력

In [ ]:
arr = np.arange(1, 101)
a = arr[(arr % 3 == 0) & (arr % 5 == 0)]
print(a)

[15 30 45 60 75 90]


Q9. 101 ~ 150 사이의 정수를 랜덤하게 추출, 2행 5열 다차원 배열을 생성 후 전치하세요

In [ ]:
arr1 = np.arange(100, 151)
arr2 = np.random.randn(2,5)



Q10. 표준정규분포로 구성된 5행 5열 다차원 배열을 생성하세요.

In [ ]:
arr = np.random.randn(5,5)
arr

array([[-0.31102571,  0.11958641,  1.14587755,  0.82437838, -0.80822583],
       [ 0.10528856, -1.08035358, -0.12571114,  0.07124983, -1.02048279],
       [-0.32932379, -2.19521574, -0.24275494,  0.46982029,  0.22661372],
       [ 2.01425267,  0.47614547,  1.20960831,  0.9392182 ,  0.17298944],
       [-1.10630458, -0.7584597 ,  0.13227496,  1.41557465,  0.39794474]])

Q11. original_array를 1차원 배열로 변환하여 출력하세요.

In [ ]:
original_array = np.array([[1, 2, 3], [4, 5, 6]])

array_1 = original_array.reshape(-1)

print(array_1)

[1 2 3 4 5 6]


Q12. 주어진 2차원 배열에서 첫 번째 행을 view로 생성하고, 이 view를 수정하여 원본 배열에 반영되도록 하세요.

original_array = np.array([[1, 2, 3], [4, 5, 6]])

In [19]:
original_array = np.array([[1, 2, 3], [4, 5, 6]])
view = original_array[0]
view[0]

print(original_array)

[[1 2 3]
 [4 5 6]]


Q13. 주어진 3차원 배열에서 첫 번째 2차원 배열을 view로 생성하고, 이 view를 수정하여 원본 배열에 반영되도록 하세요.

original_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [20]:
original_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
view = original_array[0]
view[0, 0]

print(original_array)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


Q14. 주어진 2차원 배열을 1차원 배열 view로 reshape하고, 이 view를 수정하여 원본 배열에 반영되도록 하세요.

original_array = np.array([[1, 2, 3], [4, 5, 6]])

In [21]:
original_array = np.array([[1, 2, 3], [4, 5, 6]])
view = original_array.reshape(-1)
view[0]

print(original_array)

[[1 2 3]
 [4 5 6]]


Q15. np.ones((10,10))을 아래와 같이 출력하세요.
```
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
 ```

Q16. Q. 1 ~ 100을 아래와 같이 출력하세요.

```
[[  1   2   3   4   5   6   7   8   9  10]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 81  82  83  84  85  86  87  88  89  90]
 [100  99  98  97  96  95  94  93  92  91]]
 ```

Q17. np.ones((5,5))을 아래와 같이 출력하세요.
```
[[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]]
```

Q18. np.arange(4)을 이용해서 아래와 같이 출력하세요.
```
[[0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0],
 [0, 2, 0, 0, 0],
 [0, 0, 3, 0, 0],
 [0, 0, 0, 4, 0]]
```

Q19. Q. np.zeros((8,8))을 이용해서 아래와 같이 출력하세요(두가지 방식:인덱싱, tile 함수)
```
[[0, 1, 0, 1, 0, 1, 0, 1],
[1, 0, 1, 0, 1, 0, 1, 0],
[0, 1, 0, 1, 0, 1, 0, 1],
[1, 0, 1, 0, 1, 0, 1, 0],
[0, 1, 0, 1, 0, 1, 0, 1],
[1, 0, 1, 0, 1, 0, 1, 0],
[0, 1, 0, 1, 0, 1, 0, 1],
[1, 0, 1, 0, 1, 0, 1, 0]]
```

Q20. np.arange(336).reshape(6,7,8)에서 100번째 요소의 인덱스를 구하세요.